sudo_password_hash: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30303561343563333463323537373339376166306537666334343932613638663138386135663532
  3764333032353263613464306637666561353663656161300a303861616530636461663464323239
  32393862323633366438663863616332346265366132386633623061333935336130663030383839
  6635396665323362650a633164383733303531346638386536303336306433626162636136353430
  61346163376136353838333930636635356562383431613638333838316535613638363534336164
  35386632633963663666313036386662653038333338343436393563323335333635366133373866
  31333663666262366234356631653466393135613138323136383138383430663364353632643632
  32383264633037613639623434636336336231623139323665343562656465643831313061306432
  35383730343134393462333065363532366263303933336638363966666534356636

playground_deploy_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63363162663364666430613035303863373036393365336239333261623163323035383266666363
          3561303662353262373062613265313462363838633439360a393032656235636638623934643638
          30386535356535363364633639663737613635656366333966373434396566633637316338336364
          3435643039623935320a613835346361343232663062363133396130366162653234626338306136
          64386139336337316235333030396362623164383435663737373462366235383431386536623237
          37376265393466623035623439353235663563343966336635316438616163613636373630396538
          62636363396563303838376638633161303665646438613838633830623834666534616234383865
          62393732356665336337663830666631323131643830646563633236353337636566643637653139
          39386134306264343562663735346538383438303764666130633664653564646435343534666433
          64386164663534626335313236636463616331326431653439326138613964396239396434363465
          30353732333662383865643631343331366637316662373133336331323736623937656433373131
          39386439313633623935376564643862653039653135356364343334663361616434376562363764
          63663263393439656230313962396465356361323038663232386164373839353532636132363566
          37353736303034656536346664346364316237383133623263313463393131313763326638326566
          38623238623236646665316133346162636662383331366365333737616630643264343539363039
          38346235383136313961393166323365643739396638626332346136373938656338366435353361
          39643536663537663033663239646539326233643865396339613330396632633135623361383561
          36386538646561626632356137313939353164333438363936333965616631356332363539336431
          32373830343034316561613838353334343162333535396265343632376435623239356336623665
          30333964383136313262356166653630656130336131653163626261633630643630646164326436
          34336335316164373635373364346364643734643466393338376233656463396539323463383231
          31633038383966356137393063376538303261653466346631656235383162636234326261663539
          63623666363335343862663562346431333165303930323038613533366534306532373138333661
          33643037313835663637643335663337326332646630363431616466613736343235323039346231
          3036
